project:
  type: website
  output-dir: docs
  resources:
    - "pics/"
  render:
    - "index.qmd"
    - "about.qmd"
    - "*/blogs/"
    - "!*/eda/"
    - "!*/wip_blogs"

website:
  title: "The Pretorius Perspective"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: sandstone
    css: css/styles.css    
    embed-resources: true
    toc: true